services:
  alpine:
    image: alpine:latest
    container_name: alpine
    stdin_open: true
    tty: true
    volumes: 
      - ./alpine/entrypoint.sh:/STEVE-CART/entrypoint.sh 
      - ./alpine:/STEVE-CART
    working_dir: /STEVE-CART
    command: "chmod +x /STEVE-CART/entrypoint.sh"
    entrypoint: ["sh", "/STEVE-CART/entrypoint.sh"]
    ports:
      - 8080:8080