[global_tags]
 cart_id = "$CART_ID"

[agent]
  interval = "5s"
  round_interval = true
  flush_interval = "5s"
  omit_hostname = true
  
  # === Logging ===
  debug = true
  logfile = "/var/log/telegraf/telegraf.log" 

# ===== Input plugin: Execd (Sensors) =====
[[inputs.execd]]
  command = ["/.venv/bin/python3", "/STEVECart/client/sensor_publisher/battery_publisher.py"]
  signal = "none"
  data_format = "json"
  json_time_key = "timestamp_battery"
  json_time_format = "2006-01-02T15:04:05-0700"

[[inputs.execd]]
  command = ["/.venv/bin/python3", "/STEVECart/client/sensor_publisher/nfc_publisher.py"]
  signal = "none"
  data_format = "json"
  json_time_key = "timestamp_nfc"
  json_time_format = "2006-01-02T15:04:05-0700"

[[inputs.execd]]
  command = ["/.venv/bin/python3", "/STEVECart/client/sensor_publisher/ultrasonic_publisher.py"]
  signal = "none"
  data_format = "json"
  json_time_key = "timestamp_ultrasonic"
  json_time_format = "2006-01-02T15:04:05-0700"

[[inputs.execd]]
  command = ["/.venv/bin/python3", "/STEVECart/client/sensor_publisher/scale_publisher.py"]
  signal = "none"
  data_format = "json"
  json_time_key = "timestamp_weight"
  json_time_format = "2006-01-02T15:04:05-0700"

[[inputs.execd]]
  command = ["/.venv/bin/python3", "/STEVECart/client/sensor_publisher/light_publisher.py"]
  signal = "none"
  data_format = "json"
  json_time_key = "timestamp_light"
  json_time_format = "2006-01-02T15:04:05-0700"

[[inputs.execd]]
  command = ["/.venv/bin/python3", "/STEVECart/client/sensor_publisher/uwb_publisher.py"]
  signal = "none"
  data_format = "json"
  json_time_key = "timestamp_location"
  json_time_format = "2006-01-02T15:04:05-0700"

# ===== Output plugin: MQTT (to Server) =====
[[outputs.mqtt]]
  servers = ["tcp://192.168.136.11:1883"]
  topic = "sensors/cart_data"
  data_format = "influx"
  client_id = "cart-telegraf"
  username = "admin"
  password = "adminUNIWA"

# ===== Redis Master =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.11:6378"]
#   password = "adminUNIWA"
#   tags = { role = "master" }
#   data_format = "json"

# # ===== Redis Replica 1 =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.12:6379"]
#   password = "adminUNIWA"
#   tags = { role = "rep1" }
#   data_format = "json"

#
 # ===== Redis Replica 2 =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.13:6380"]
#   password = "adminUNIWA"
#   tags = { role = "rep2" }
#   data_format = "json"

# # ===== Redis Sentinels =====
# [[inputs.redis]]
#   servers = [
#     "tcp://192.168.136.11:26378",
#     "tcp://192.168.136.12:26379",
#     "tcp://192.168.136.13:26380"
#   ]
#   tags = { role = "sentinel" }
#   data_format = "json"
