[global_tags]
 cart_id = "$CART_ID"

[agent]
  interval = "5s"
  round_interval = true
  flush_interval = "5s"
  omit_hostname = true

# ===== Input plugin: Execd (Sensors) =====
[[inputs.execd]]
  command = ["/STEVE-CART/battery_publisher"]
  signal = "none"
  data_format = "json"

[[inputs.execd]]
  command = ["/STEVE-CART/nfc_publisher"]
  signal = "none"
  data_format = "json"

[[inputs.execd]]
  command = ["/STEVE-CART/ultrasonic_publisher"]
  signal = "none"
  data_format = "json"

[[inputs.execd]]
  command = ["/STEVE-CART/weight_publisher"]
  signal = "none"
  data_format = "json"

[[inputs.execd]]
  command = ["/STEVE-CART/UWB_TAG.sh"]
  signal = "none"
  data_format = "json"

# ===== Output plugin: MQTT (to Server) =====
[[outputs.mqtt]]
  servers = ["tcp://192.168.136.11:1883"]
  topic = "sensors/cart_data"
  data_format = "json"
  client_id = "cart-telegraf"
  username = "admin"
  password = "adminUNIWA"

# ===== Redis Master =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.11:6378"]
#   password = "adminUNIWA"
#   tags = { role = "master" }
#   data_format = "json"

# # ===== Redis Replica 1 =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.12:6379"]
#   password = "adminUNIWA"
#   tags = { role = "rep1" }
#   data_format = "json"

#
 # ===== Redis Replica 2 =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.13:6380"]
#   password = "adminUNIWA"
#   tags = { role = "rep2" }
#   data_format = "json"

# # ===== Redis Sentinels =====
# [[inputs.redis]]
#   servers = [
#     "tcp://192.168.136.11:26378",
#     "tcp://192.168.136.12:26379",
#     "tcp://192.168.136.13:26380"
#   ]
#   tags = { role = "sentinel" }
#   data_format = "json"
