package initializers

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"steve-api/models"
	"time"

	mqtt "github.com/eclipse/paho.mqtt.golang"
)

func handleNFCScan(nfcTag string, cartID string) {
	if DB == nil {
		fmt.Println("Database not initialized.")
		return
	}
	var product models.Product
	var cart models.Cart

	// Find the product by nfcTag
	if err := DB.Where("nfc_tag = ?", nfcTag).First(&product).Error; err != nil {
		fmt.Println("Error: Product not found for NFC Tag:", nfcTag)
		return
	}

	// Find the cart by cartID
	if err := DB.Where("cart_id = ?", cartID).First(&cart).Error; err != nil {
		fmt.Println("Error: Cart not found for Cart ID:", cartID)
		return
	}

	// Add to cart operator items
	var cartOperatorItem models.CartOperatorItem
	cartOperatorItem.UserCartID = cart.ID
	cartOperatorItem.ProductID = product.ID
	cartOperatorItem.Quantity = 1
	if err := DB.Save(&cartOperatorItem).Error; err != nil {
		fmt.Println("Error: Could not save cart operator item:", err)
		return
	}

	// Update cart total price and weight
	cart.TotalPrice += product.Price
	cart.TotalWeight += product.Weight
	if err := DB.Save(&cart).Error; err != nil {
		fmt.Println("Error: Could not update cart totals:", err)
		return
	}

	fmt.Printf("Success! Added product %s to Cart %s. New total price: %.2f\n", product.ProductName, cart.Cart_ID, cart.TotalPrice)
}

var messagePubHandler mqtt.MessageHandler = func(client mqtt.Client, msg mqtt.Message) {
	var payloadData map[string]interface{}

	err := json.Unmarshal(msg.Payload(), &payloadData)
	if err != nil {
		fmt.Println("Can't read JSON payload: ", err)
		return
	}

	// Extract "fields" wrapper generated by Telegraf
	var fields map[string]interface{}
	if f, ok := payloadData["fields"].(map[string]interface{}); ok {
		fields = f
	} else {
		// Fallback for raw JSON
		fields = payloadData
	}

	// Extract tags to get cart_id
	var cartID string
	if tags, ok := payloadData["tags"].(map[string]interface{}); ok {
		if cID, ok := tags["cart_id"].(string); ok {
			cartID = cID
		}
	}

	if nfcVal, ok := fields["NFC_data"]; ok {
		fmt.Println("NFC Scan Detected!")
		if nfcStr, ok := nfcVal.(string); ok {
			if cartID != "" && cartID != "$CART_ID" {
				handleNFCScan(nfcStr, cartID)
			} else {
				fmt.Println("Warning: Could not process NFC scan because cart_id is missing or un-templated.")
			}
		}
	} else if _, ok := fields["weight_kg"]; ok {
		fmt.Println("Weight Detected!")
	} else if _, ok := fields["distance_cm"]; ok {
		fmt.Println("Distance Detected!")
	} else if _, ok := fields["lux"]; ok {
		fmt.Println("Lux Detected!")
	} else if _, ok := fields["x_coordinate"]; ok {
		fmt.Println("UWB Detected!")
	} else if _, ok := fields["battery_level"]; ok {
		fmt.Println("Battery Detected!")
	} else {
		fmt.Printf("Unknown Payload Format: %s\n", msg.Payload())
	}
}

var connectHandler mqtt.OnConnectHandler = func(client mqtt.Client) {
	fmt.Println("Connected")
}

var connectLostHandler mqtt.ConnectionLostHandler = func(client mqtt.Client, err error) {
	fmt.Printf("Connect lost: %v", err)
}

func initMQTT() {
	var WeightData models.WeightData
	WeightData.Value = 0.0
	WeightData.StableWeight = false
	WeightData.Timestamp = time.Now()

	var NFCData models.NFCData
	NFCData.TagID = "0000"
	NFCData.ScannerID = "sc_01"

	var UltraSonicData models.UltraSonicData
	UltraSonicData.Distance = 0.0
	UltraSonicData.Timestamp_Distance = time.Now()

	var UltraSonicData2 models.UltraSonicData
	UltraSonicData2.Distance = 0.0
	UltraSonicData2.Timestamp_Distance = time.Now()

	var BatteryData models.BatteryData
	BatteryData.BatLevel = 100.0
	BatteryData.Charging = false

	var LightSensorData models.LightSensorData
	LightSensorData.LuxLevel = 0.0
	LightSensorData.Timestamp_Lux = time.Now()

	var UWBData models.UWBData
	UWBData.X_Coordinate = 0.0
	UWBData.Y_Coordinate = 0.0
	UWBData.Z_Coordinate = 0.0
	UWBData.Timestamp_UWB = time.Now()
}

func ConnectMQTT() mqtt.Client {
	broker := os.Getenv("MQTT_BROKER")
	user := os.Getenv("MQTT_USER")
	pass := os.Getenv("MQTT_PASS")
	opts := mqtt.NewClientOptions()
	opts.AddBroker(broker)
	opts.SetClientID("go_mqtt_client")
	opts.SetUsername(user)
	opts.SetPassword(pass)

	jsonFile, err := os.Open("config.json")
	if err != nil {
		fmt.Println(err)
	}
	defer jsonFile.Close()
	byteValue, _ := io.ReadAll(jsonFile)
	var result map[string]interface{}

	json.Unmarshal(byteValue, &result)
	opts.SetDefaultPublishHandler(messagePubHandler)
	opts.SetOnConnectHandler(connectHandler)
	opts.SetConnectionLostHandler(connectLostHandler)
	client := mqtt.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	return client
}

func publish(client mqtt.Client) {
	num := 10
	for i := 0; i < num; i++ {
		text := fmt.Sprintf("Message: %d", i)
		token := client.Publish("sensors/cart_data", 0, false, text)
		token.Wait()
		time.Sleep(time.Second)
	}
}

func Sub(client mqtt.Client) {
	topic := "sensors/cart_data"
	token := client.Subscribe(topic, 1, nil)
	token.Wait()
	fmt.Printf("Subscribed to topic: %s", topic)
}
