package initializers

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"math"
	"os"
	"regexp"
	"strconv"
	"steve-api/models"
	"time"

	mqtt "github.com/eclipse/paho.mqtt.golang"
)

// UWBBroadcast is read by controllers.StartUWBBroadcaster() to fan out
// live positions to all connected WebSocket clients.
var UWBBroadcast = make(chan models.UWBData, 100)

func handleNFCScan(nfcTag string, cartID string) {
	if DB == nil {
		fmt.Println("Database not initialized.")
		return
	}
	var product models.Product
	var cart models.Cart

	// Find the product by nfcTag
	if err := DB.Where("nfc_tag = ?", nfcTag).First(&product).Error; err != nil {
		fmt.Println("Error: Product not found for NFC Tag:", nfcTag)
		return
	}

	// Find the cart by cartID
	if err := DB.Where("cart_id = ?", cartID).First(&cart).Error; err != nil {
		fmt.Println("Error: Cart not found for Cart ID:", cartID)
		return
	}

	// Add to cart operator items
	var cartOperatorItem models.CartOperatorItem
	cartOperatorItem.UserCartID = cart.ID
	cartOperatorItem.ProductID = product.ID
	cartOperatorItem.Quantity = 1
	if err := DB.Save(&cartOperatorItem).Error; err != nil {
		fmt.Println("Error: Could not save cart operator item:", err)
		return
	}

	// Update cart total price and weight
	cart.TotalPrice += product.Price
	cart.TotalWeight += product.Weight
	if err := DB.Save(&cart).Error; err != nil {
		fmt.Println("Error: Could not update cart totals:", err)
		return
	}

	fmt.Printf("Success! Added product %s to Cart %s. New total price: %.2f\n", product.ProductName, cart.Cart_ID, cart.TotalPrice)
}

func handleWeightScan(weight_kg float64, cartID string) {
	if DB == nil {
		fmt.Println("Database not initialized.")
		return
	}
	var cart models.Cart

	// Find the cart by cartID
	if err := DB.Where("cart_id = ?", cartID).First(&cart).Error; err != nil {
		fmt.Println("Error: Cart not found for Cart ID:", cartID)
		return
	}

	// Update cart total weight
	cart.TotalWeight += float32(weight_kg)
	if err := DB.Save(&cart).Error; err != nil {
		fmt.Println("Error: Could not update cart total weight:", err)
		return
	}

	fmt.Printf("Success! Added %f kg to Cart %s. New total weight: %.2f\n", weight_kg, cart.Cart_ID, cart.TotalWeight)
}

func handleDistanceScan(distance_cm float64, cartID string) {
	// Υπέρηχος (εμπόδια): Δεν χρειάζεται να αποθηκεύεται αθροιστικά στο Cart
	fmt.Printf("Cart %s is %f cm away from obstacle.\n", cartID, distance_cm)
}

var messagePubHandler mqtt.MessageHandler = func(client mqtt.Client, msg mqtt.Message) {
	var payloadData map[string]interface{}

	err := json.Unmarshal(msg.Payload(), &payloadData)
	if err != nil {
		fmt.Println("Can't read JSON payload: ", err)
		return
	}

	// Extract "fields" wrapper generated by Telegraf
	var fields map[string]interface{}
	if f, ok := payloadData["fields"].(map[string]interface{}); ok {
		fields = f
	} else {
		// Fallback for raw JSON
		fields = payloadData
	}

	// Extract tags to get cart_id
	var cartID string
	if tags, ok := payloadData["tags"].(map[string]interface{}); ok {
		if cID, ok := tags["cart_id"].(string); ok {
			cartID = cID
		}
	}

	if nfcVal, ok := fields["NFC_data"]; ok {
		fmt.Println("NFC Scan Detected!")
		if nfcStr, ok := nfcVal.(string); ok {
			if cartID != "" && cartID != "$CART_ID" {
				handleNFCScan(nfcStr, cartID)
			} else {
				fmt.Println("Warning: Could not process NFC scan because cart_id is missing or un-templated.")
			}
		}
	} else if _, ok := fields["weight"]; ok {
		fmt.Println("Weight Detected!")

	} else if _, ok := fields["distance"]; ok {
		fmt.Println("Distance Detected!")
	} else if _, ok := fields["lux"]; ok {
		fmt.Println("Lux Detected!")
	} else if rangeVal, ok := fields["range"]; ok {
		fmt.Println("UWB Detected! Raw range string:", rangeVal)
		
		rangeStr, isString := rangeVal.(string)
		if !isString {
			fmt.Println("Error: range is not a string")
			return
		}

		re := regexp.MustCompile(`[0-9]+\.[0-9]+`)
		matches := re.FindAllString(rangeStr, -1)
		
		if len(matches) < 3 {
			fmt.Println("Warning: Could not find 3 distances in the UWB string:", rangeStr)
		} else {
			d1, _ := strconv.ParseFloat(matches[0], 64)
			d2, _ := strconv.ParseFloat(matches[1], 64)
			d3, _ := strconv.ParseFloat(matches[2], 64)

			// 2. Παίρνουμε τις θέσεις των 3 Anchors από την MariaDB (ShelvePosition table)
			var anchors []models.ShelvePosition
			DB.Order("shelve_id asc").Limit(3).Find(&anchors)

			if len(anchors) < 3 {
				fmt.Println("Error: Need at least 3 configured shelves (anchors) in DB to do trilateration!")
			} else {
				// 3. Μαθηματικός τύπος Τριγωνοποίησης (Trilateration)
				x1, y1 := anchors[0].X_Coordinate, anchors[0].Y_Coordinate
				x2, y2 := anchors[1].X_Coordinate, anchors[1].Y_Coordinate
				x3, y3 := anchors[2].X_Coordinate, anchors[2].Y_Coordinate

				A := 2*x2 - 2*x1
				B := 2*y2 - 2*y1
				C := math.Pow(d1, 2) - math.Pow(d2, 2) - math.Pow(x1, 2) + math.Pow(x2, 2) - math.Pow(y1, 2) + math.Pow(y2, 2)

				D := 2*x3 - 2*x2
				E := 2*y3 - 2*y2
				F := math.Pow(d2, 2) - math.Pow(d3, 2) - math.Pow(x2, 2) + math.Pow(x3, 2) - math.Pow(y2, 2) + math.Pow(y3, 2)

				denominator := (E*A - B*D)
				if math.Abs(denominator) < 0.0001 {
					fmt.Println("Error: Anchors are collinear, trilateration failed.")
				} else {
					x := (C*E - F*B) / denominator
					y := (C*D - A*F) / (B*D - A*E)

					nodeID := cartID
					uwbData := models.UWBData{
						UWB_NODEID:   nodeID,
						X_Coordinate: x,
						Y_Coordinate: y,
						LastSeen_UWB: time.Now(),
						Description:  "Live MQTT position (Trilaterated)",
					}

					var existing models.UWBData
					if err := DB.Where("uwb_node_id = ?", nodeID).First(&existing).Error; err == nil {
						existing.X_Coordinate = x
						existing.Y_Coordinate = y
						existing.LastSeen_UWB = time.Now()
						DB.Save(&existing)
					} else {
						DB.Create(&uwbData)
					}
					
					// Αποστολή στο Minimap!
					select {
					case UWBBroadcast <- uwbData:
						fmt.Printf("Trilateration Success! Cart %s is at X:%.2f, Y:%.2f\n", nodeID, x, y)
					default:
						log.Println("Warning: UWBBroadcast channel full, position dropped")
					}
				}
			}
		}
	} else if _, ok := fields["battery_level"]; ok {
		fmt.Println("Battery Detected!")
	} else {
		fmt.Printf("Unknown Payload Format: %s\n", msg.Payload())
	}
}

var connectHandler mqtt.OnConnectHandler = func(client mqtt.Client) {
	fmt.Println("Connected")
}

var connectLostHandler mqtt.ConnectionLostHandler = func(client mqtt.Client, err error) {
	fmt.Printf("Connect lost: %v", err)
}

func initMQTT() {
	var WeightData models.WeightData
	WeightData.Value = 0.0
	WeightData.StableWeight = false
	WeightData.Timestamp = time.Now()

	var NFCData models.NFCData
	NFCData.TagID = "0000"
	NFCData.ScannerID = "sc_01"

	var UltraSonicData models.UltraSonicData
	UltraSonicData.Distance = 0.0
	UltraSonicData.Timestamp_Distance = time.Now()

	var UltraSonicData2 models.UltraSonicData
	UltraSonicData2.Distance = 0.0
	UltraSonicData2.Timestamp_Distance = time.Now()

	var BatteryData models.BatteryData
	BatteryData.BatLevel = 100.0
	BatteryData.Charging = false

	var LightSensorData models.LightSensorData
	LightSensorData.LuxLevel = 0.0
	LightSensorData.Timestamp_Lux = time.Now()

	var UWBData models.UWBData
	UWBData.X_Coordinate = 0.0
	UWBData.Y_Coordinate = 0.0
	UWBData.LastSeen_UWB = time.Now()
}

func ConnectMQTT() mqtt.Client {
	broker := os.Getenv("MQTT_BROKER")
	user := os.Getenv("MQTT_USER")
	pass := os.Getenv("MQTT_PASS")
	opts := mqtt.NewClientOptions()
	opts.AddBroker(broker)
	opts.SetClientID("go_mqtt_client")
	opts.SetUsername(user)
	opts.SetPassword(pass)

	jsonFile, err := os.Open("config.json")
	if err != nil {
		fmt.Println(err)
	}
	defer jsonFile.Close()
	byteValue, _ := io.ReadAll(jsonFile)
	var result map[string]interface{}

	json.Unmarshal(byteValue, &result)
	opts.SetDefaultPublishHandler(messagePubHandler)
	opts.SetOnConnectHandler(connectHandler)
	opts.SetConnectionLostHandler(connectLostHandler)
	client := mqtt.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	return client
}

func publish(client mqtt.Client) {
	num := 10
	for i := 0; i < num; i++ {
		text := fmt.Sprintf("Message: %d", i)
		token := client.Publish("sensors/cart_data", 0, false, text)
		token.Wait()
		time.Sleep(time.Second)
	}
}

func Sub(client mqtt.Client) {
	topic := "sensors/cart_data"
	token := client.Subscribe(topic, 1, nil)
	token.Wait()
	fmt.Printf("Subscribed to topic: %s", topic)
}
