services:
  golang:
    image: golang:latest
    ports:
      - target: 8089
        published: 8089
        protocol: tcp
    networks:
      - smartcart_network
      - sensors_network
    volumes:
      - ./steve-api/:/app
    working_dir: /app
    entrypoint: ["/app/entrypoint.sh"]
    environment:
      - DB_URL=uniwa_admin:adminUNIWA@tcp(mariadb_1:3306)/supermarket_db?tls=skip-verify
      - DB_HOST=mariadb_1
      - DB_NAME=supermarket_db
      - INFLUX_DB=http://influxdb:8086
      - INFLUX_TOKEN=adminUNIWAsuper
      - MQTT_BROKER=tcp://mosquitto:1884
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      placement:
        constraints:
          - node.role == manager

  influxdb:
    image: influxdb:2.7.12
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_logs:/var/log/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminUNIWA
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=adminUNIWAsuper
      - DOCKER_INFLUXDB_INIT_ORG=UNIWA
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors
    networks:
      - sensors_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5


  # PRIMARY NODE
  mariadb_1:
    image: mariadb:latest
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    configs:
      - source: mysql_ca_cert
        target: /etc/mysql/certs/ca.pem
      - source: mysql_server_cert
        target: /etc/mysql/certs/server-cert.pem
      - source: mysql_server_key
        target: /etc/mysql/certs/server-key.pem
      - source: mysql_init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootUNIWA
      MYSQL_DATABASE: supermarket_db
      MYSQL_USER: uniwa_admin
      MYSQL_PASSWORD: adminUNIWA
    # Use standard names in gcomm address
    command: >
      --wsrep_on=ON
      --binlog_format=ROW
      --wsrep_provider=/usr/lib/galera/libgalera_smm.so
      --wsrep_cluster_name=mariadb_cluster
      --wsrep_node_name=node_1
      --wsrep_cluster_address=gcomm://
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --ssl-ca=/etc/mysql/certs/ca.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
    networks:
      smartcart_network:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      placement:
        constraints:
          - node.role == manager

  # SECONDARY NODE
  mariadb_2:
    image: mariadb:latest
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
    configs:
      - source: mysql_ca_cert
        target: /etc/mysql/certs/ca.pem
      - source: mysql_server_cert
        target: /etc/mysql/certs/server-cert.pem
      - source: mysql_server_key
        target: /etc/mysql/certs/server-key.pem
    environment:
      MYSQL_ROOT_PASSWORD: rootUNIWA
      MYSQL_DATABASE: supermarket_db
      MYSQL_USER: uniwa_admin
      MYSQL_PASSWORD: adminUNIWA
    # Connects to node_1
    command: >
      --wsrep_on=ON
      --wsrep_cluster_name=mariadb_cluster
      --wsrep_node_name=node_2
      --wsrep_provider=/usr/lib/galera/libgalera_smm.so
      --binlog_format=ROW
      --wsrep_cluster_address=gcomm://mariadb_1,mariadb_2,mariadb_3
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --ssl-ca=/etc/mysql/certs/ca.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
    networks:
      smartcart_network:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  # TERTIARY NODE
  mariadb_3:
    image: mariadb:latest
    ports:
      - target: 3306
        published: 3308
        protocol: tcp
    configs:
      - source: mysql_ca_cert
        target: /etc/mysql/certs/ca.pem
      - source: mysql_server_cert
        target: /etc/mysql/certs/server-cert.pem
      - source: mysql_server_key
        target: /etc/mysql/certs/server-key.pem
    environment:
      MYSQL_ROOT_PASSWORD: rootUNIWA
      MYSQL_DATABASE: supermarket_db
      MYSQL_USER: uniwa_admin
      MYSQL_PASSWORD: adminUNIWA
    # Connects to node_1
    command: >
      --wsrep_on=ON
      --binlog_format=ROW
      --wsrep_provider=/usr/lib/galera/libgalera_smm.so
      --wsrep_cluster_name=mariadb_cluster
      --wsrep_node_name=node_3
      --wsrep_cluster_address=gcomm://mariadb_1,mariadb_2,mariadb_3
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --ssl-ca=/etc/mysql/certs/ca.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
    networks:
      smartcart_network:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
        - target: 1883
          published: 1884
          protocol: tcp
        - target: 9001
          published: 9001
          protocol: tcp
    configs:
      - source: mqtt_conf
        target: /mosquitto/config/mosquitto.conf
        uid: '1883'
        gid: '1883'
        mode: 0644
      - source: pwfile
        target: /mosquitto/config/pwfile
        uid: '1883'
        gid: '1883'
        mode: 0700
      - source: acl_file
        target: /mosquitto/config/acl_file
        uid: '1883'
        gid: '1883'
        mode: 0700
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - sensors_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

networks:
  smartcart_network:
    driver: overlay
    attachable: true
  sensors_network:
    driver: overlay
    attachable: true

volumes:
  influxdb_data:
  influxdb_logs:
  mosquitto_data:
  mosquitto_log:
  
configs:
  mysql_ca_cert:
    external: true
  mysql_server_cert:
    external: true
  mysql_server_key:
    external: true
  mysql_init_sql:
    external: true
  mqtt_conf:
    external: true
  pwfile:
    external: true
  acl_file:
    external: true

# Leave Swarm if needed (already in Swarm)
# docker stack deploy -c server.yml smartcart

# Check services
# docker stack services smartcart

# Remove stack
# docker stack rm smartcart
# https://docs.percona.com/percona-xtradb-cluster/8.0/docker.html
# docker service ps smartcart_golang --no-trunc