[agent]
  interval = "5s"
  round_interval = true
  flush_interval = "5s"
  omit_hostname = true

# ===== Input plugin: MQTT Consumer =====
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"] #tcp://192.168.136.11:1883
  topics = ["sensors/cart_data"]
  client_id = "telegraf-server-consumer"
  username = "admin"
  password = "adminUNIWA"
  qos = 0
  connection_timeout = "30s"
  persistent_session = false
  data_format = "json"

# ===== Output plugin: InfluxDB v2 =====
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"] #http://192.168.136.11:8085
  token = "adminUNIWAsuper"  
  organization = "UNIWA"
  bucket = "sensors"

# ===== Redis Master =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.11:6378"]
#   password = "adminUNIWA"
#   tags = { role = "master" }
#   data_format = "json"

# # ===== Redis Replica 1 =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.12:6379"]
#   password = "adminUNIWA"
#   tags = { role = "rep1" }
#   data_format = "json"

# # ===== Redis Replica 2 =====
# [[inputs.redis]]
#   servers = ["tcp://192.168.136.13:6380"]
#   password = "adminUNIWA"
#   tags = { role = "rep2" }
#   data_format = "json"

# # ===== Redis Sentinels =====
# [[inputs.redis]]
#   servers = [
#     "tcp://192.168.136.11:26378",
#     "tcp://192.168.136.12:26379",
#     "tcp://192.168.136.13:26380"
#   ]
#   tags = { role = "sentinel" }
#   data_format = "json"
