services:
    influxdb:
        image: influxdb:2.7.12 
        container_name: influxdb
        ports:
          - "8085:8086"
        volumes:
          - ./influxdb/influxdb_data:/var/lib/influxdb
          - ./influxdb/influxdb_logs:/var/log/influxdb
        environment:
          - DOCKER_INFLUXDB_INIT_MODE=setup
          - DOCKER_INFLUXDB_INIT_USERNAME=admin
          - DOCKER_INFLUXDB_INIT_PASSWORD=adminUNIWA
          - DOCKER_INFLUXDB_INIT_BUCKET=sensors
          - DOCKER_INFLUXDB_INIT_ORG=UNIWA
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        ports:
          - "3306:3306"
        volumes:
          - ./mariadb/mariadb_data:/var/lib/mysql
          - ./mariadb/init.sql:/db/init.sql
        entrypoint: ["docker-entrypoint.sh", "--init-file", "/db/init.sql"]
        environment:
          - MYSQL_DATABASE=supermarket_db
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
